service: versionwatcher

provider:
    name: aws
    runtime: nodejs4.3
    profile: versionwatcher
    stage: stage
    region: eu-west-1

functions:
    trackPHP:
        handler: phpHandler.trackPHP
        description: Track PHP dependencies
        events: # The Events that trigger this Function
            - http:
                path: watcher/track-php # Path for this endpoint
                method: post # HTTP method for this endpoint
