service: versionwatcher

provider:
    name: aws
    runtime: nodejs4.3
    profile: versionwatcher
    stage: stage
    region: eu-west-1

functions:
    trackWp:
        handler: handlers.wp
        description: Track Wordpress dependencies
        events:
            - http:
                path: tracker/wp
                method: post
                private: true

    trackNode:
        handler: handlers.node
        description: Track Node.js dependencies
        events:
            - http:
                path: tracker/node
                method: post
                private: true

    trackPython:
        handler: handlers.python
        description: Track python dependencies
        events:
            - http:
                path: tracker/python
                method: post
                private: true

    stableHandler:
        handler: handlers.stableHandler
        description: List stable versions
        events:
            - http:
                path: tracker/stable
                method: get
                private: true

resources:
    Resources:
        DynamoDBIamPolicy:
            Type: AWS::IAM::Policy
    Properties:
        PolicyName: lambda-dynamodb
        PolicyDocument:
            Version: '2012-10-17'
        Statement:
            - Effect: Allow
              Action:
                  - dynamodb:PutItem
            - dynamodb:GetItem
            - dynamodb:Query
            - dynamodb:Scan
        Resource:
            - arn:aws:dynamodb:*:*:table/VersionWatcherVersion
            - arn:aws:dynamodb:*:*:table/VersionWatcherStable
            - arn:aws:dynamodb:*:*:table/VersionWatcherPackage
        Roles:
            - Ref: IamRoleLambdaExecution
